services:
  mariadb-database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mariadb_database
    restart: always
    ports:
        - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sevensuite
      MYSQL_USER: sevensuiteuser
      MYSQL_PASSWORD: development-sevensuiteapp
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      mariadb_network:
        ipv4_address: 192.168.1.5
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin-mariadb:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_mariadb
    depends_on:
      - mariadb-database
    environment:
      PMA_HOST: mariadb-database
      PMA_USER: sevensuiteuser
      PMA_PASSWORD: development-sevensuiteapp
    ports:
      - "81:80"
    networks:
      mariadb_network:
        ipv4_address: 192.168.1.10

  sevensuite:
    build:
      context: ../
      dockerfile: /docker/app/Dockerfile
    environment:
      DATABASE_URI: mariadb+mariadbconnector://sevensuiteuser:development-sevensuiteapp@mariadb-database:3306/sevensuite
      FLASK_ENV: development
    ports:
      - "8080:8080"
      - "5000:5000"
    depends_on:
      mariadb-database:
        condition: service_healthy
    networks:
      mariadb_network:
        ipv4_address: 192.168.1.15

  nextcloud-database:
    image: mariadb:latest
    container_name: nextcloud_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nextcloud_db
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: user_password
    volumes:
      - nextcloud_db_data:/var/lib/mysql

  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud_app
    restart: always
    ports:
      - "8082:80"
    environment:
      MYSQL_HOST: nextcloud-database
      MYSQL_DATABASE: nextcloud_db
      MYSQL_USER: nextcloud_user
      MYSQL_PASSWORD: user_password
      NEXTCLOUD_ADMIN_USER: admin_username
      NEXTCLOUD_ADMIN_PASSWORD: admin_password
    depends_on:
      - nextcloud-database
    volumes:
      - nextcloud_data:/var/www/html

volumes:
  mariadb_data:
  nextcloud_data:
  nextcloud_db_data:

networks:
  mariadb_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24