# 1. Use the official MariaDB image as a parent image
FROM mariadb:10.5

# 2. Set the working directory
WORKDIR /usr/src/app

# 3. Export the port
EXPOSE 3306

# 4. Añadimos un punto de entrada para inicializar MariaDB
CMD ["mysqld"]
